name: histgen

on:
  schedule:
    - cron:  '1 13 * * *'

jobs:
  histgen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run histgen
      run: ./histgen
      shell: bash
